language: c
compiler: clang

addons:
  apt:
    packages:
      - make
      - valgrind
      - libevent-dev

install:
  - go get github.com/gosuri/uiprogress
  - go get github.com/cespare/xxhash

script:
  - make test-splice COVERAGE=1 DEBUG=1

after_success:
  - bash <(curl -s https://codecov.io/bash)

