language: c
compiler: clang

jobs:
  include:
    - env: NOLIBEVENT=1
    - if: branch != coverity-scan
      env: USELIBEVENT=1 SPEED_FACTOR=2

addons:
  apt:
    packages:
      - valgrind
      - libevent-dev
  sonarcloud:
    organization: "davylandman-github"

install:
  - go version
  - go get github.com/gosuri/uiprogress
  - go get github.com/cespare/xxhash

script:
  - make clean test COVERAGE=1 DEBUG=1

after_success:
  - sonar-scanner
  -  if [ "$TRAVIS_BRANCH" != "coverity-scan" ]; then bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov"; fi

