language: c
compiler: clang

addons:
  apt:
    packages:
      - valgrind
      - libevent-dev
  coverity_scan:
    project:
      name: "DavyLandman/l7knockknock"
      description: "l7 knock knock hidden proxy"
    notification_email: davy.landman@gmail.com
    build_command: make 
    branch_pattern: coverity_scan

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


install:
  - go version
  - go get github.com/gosuri/uiprogress
  - go get github.com/cespare/xxhash

script:
  - make test COVERAGE=1 DEBUG=1

after_success:
  - bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov"

