language: c
compiler: clang

addons:
  apt:
    packages:
      - valgrind
      - libevent-dev

install:
  - go version
  - go get github.com/gosuri/uiprogress
  - go get github.com/cespare/xxhash

script:
  - make test COVERAGE=1 DEBUG=1

after_success:
  - find . -type f -name '*.gcda' | xargs llvm-cov gcov -pb
  - bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov"

