language: go

jobs:
  include:
    - env: NOLIBEVENT=1
    - env: USELIBEVENT=1 SPEED_FACTOR=2

addons:
  apt:
    packages:
      - valgrind
      - libevent-dev
  sonarcloud:
    organization: "davylandman-github"
    

install:
  - go version
  - go get github.com/gosuri/uiprogress
  - go get github.com/cespare/xxhash

script:
  - build-wrapper-linux-x86-64 --out-dir output make clean test COVERAGE=1 DEBUG=1

after_success:
  -  if [ "$NOLIBEVENT" = "1" ]; then fsonar-scanner -Dsonar.sources=. -Dsonar.projectKey="DavyLandman_l7knockknock" -Dsonar.cfamily.build-wrapper-output=output; fi
  -  if [ "$TRAVIS_BRANCH" != "coverity-scan" ]; then bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov"; fi

